In [1]:
import numpy

In [2]:
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
m = numpy.asarray([[123,123,123,123,123],[],[]])

In [6]:
m

array([list([123, 123, 123, 123, 123]), list([]), list([])], dtype=object)

In [7]:
type(m)

numpy.ndarray

In [8]:
import cv2
im_g = cv2.imread("smallgray.png", 1)

In [9]:
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
cv2.imwrite("second_grey.png", im_g)

True

In [11]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [13]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [14]:
ims = numpy.hstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
ims = numpy.vstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
hs = numpy.hsplit(ims,5)
print(hs)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [17]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
vs = numpy.vsplit(ims,3)
vs

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]